//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diga.WebView2.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diga.WebView2.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die data:text/css;charset=utf8;base64,LyogQ29weXJpZ2h0IChjKSAyMDEyIFRoZSBDaHJvbWl1bSBBdXRob3JzLiBBbGwgcmlnaHRzIHJlc2VydmVkLg0KICogVXNlIG9mIHRoaXMgc291cmNlIGNvZGUgaXMgZ292ZXJuZWQgYnkgYSBCU0Qtc3R5bGUgbGljZW5zZSB0aGF0IGNhbiBiZQ0KICogZm91bmQgaW4gdGhlIExJQ0VOU0UgZmlsZS4gKi8NCg0KLyogQSBidXR0ZXIgYmFyIGlzIGFuIG5vbi1tb2RhbCBub3RpZmljYXRpb24sIHVzdWFsbHkgeWVsbG93LCB0aGF0IGFwcGVhcnMgYXQNCiAqIHRoZSB0b3Agb2YgdGhlIHNjcmVlbi4gR2VuZXJhbGx5LCB0aGV5IHNob3VsZCBjb250YWluIGEgc2luZ2xlIGxpbmUgb2YgdGV4dCwNCiAqIGFuZCBvbmUgb3IgdHdvIGxpbm [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string resources_css_button_bar_css {
            get {
                return ResourceManager.GetString("resources/css/button_bar.css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die data:text/css;charset=utf-8;base64,OnJvb3R7DQogICAgIC0tZGlnYS1idG4tYWN0aXZlLWJnOiByZ2IoMCwgMTIwLCAyMTIpOw0KICAgICAtLWRpZ2EtYnRuLWFjdGl2ZS1ib3JkZXItY29sb3I6IHJnYigwLCAwLCAwKTsNCiAgICAgLS1kaWdhLWJ0bi1hY3RpdmUtaG9vdmVyLWNvbG9yOiByZ2IoMCwgMTA3LCAxODkpOw0KICAgICAtLWRpZ2EtYnRuLWFjdGl2ZS10ZXh0LWNvbG9yOiByZ2IoMjU1LDI1NSwyNTUpOw0KICAgICAtLWRpZ2EtYnRuLWFjdGl2ZS1hY3RpdmUtY29sb3I6IHJnYigwLCA5NiwgMTcwKTsNCiAgICAgLS1kaWdhLWJ0bi1ub3JtLWJnOiByZ2IoMjM5LCAyMzksIDIzOSk7DQogICAgIC0tZGlnYS1idG4tbm9ybS1ob292ZXItY29sb3I6cmdiKDIyO [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string resources_css_diga_css {
            get {
                return ResourceManager.GetString("resources/css/diga.css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die data:text/html;charset=utf-8;base64,PGh0bWw+DQo8aGVhZD4NCiAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+DQo8L2hlYWQ+DQo8Ym9keT4NCiAgICA8YnV0dG9uIG9uY2xpY2s9ImFsZXJ0KCdoYWxsbycpOyI+dGVzdDwvYnV0dG9uPg0KPC9ib2R5Pg0KPC9odG1sPg== ähnelt.
        /// </summary>
        public static string resources_test_html {
            get {
                return ResourceManager.GetString("resources/test.html", resourceCulture);
            }
        }
    }
}
