// Decompiled with JetBrains decompiler
// Type: WebView2.COREWEBVIEW2_PROCESS_FAILED_KIND
// Assembly: WebView2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 6399528E-A51C-4F53-9554-F4718EFA3992
// Assembly location: O:\webview2\V9579\WebView2.dll

namespace Diga.WebView2.Interop
{
  public enum COREWEBVIEW2_PROCESS_FAILED_KIND
  {
    COREWEBVIEW2_PROCESS_FAILED_KIND_BROWSER_PROCESS_EXITED,
    COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED,
    COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_UNRESPONSIVE,
  }
}
