// Decompiled with JetBrains decompiler
// Type: WebView2.CORE_WEBVIEW2_WEB_ERROR_STATUS
// Assembly: WebView2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 390039CF-BF77-421E-8AE4-CC8FD0DF2A08
// Assembly location: O:\dev\webview2-interop-master\Src\WebView2.dll

namespace Diga.WebView2.Interop
{
  public enum CORE_WEBVIEW2_WEB_ERROR_STATUS
  {
    CORE_WEBVIEW2_WEB_ERROR_STATUS_UNKNOWN,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_TIMEOUT,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED,
    CORE_WEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR,
  }
}
