// Decompiled with JetBrains decompiler
// Type: WebView2Experimental.COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS
// Assembly: WebView2Experimental, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 2FA7ABB2-ECD1-41D1-96C7-3EF46A31C524
// Assembly location: O:\webview2\V9515\WebView2Experimental.dll

namespace Diga.WebView2.Interop.Experimental
{
  public enum COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS
  {
    COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_NONE = 0,
    COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_LEFT_BUTTON = 1,
    COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_RIGHT_BUTTON = 2,
    COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_SHIFT = 4,
    COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_CONTROL = 8,
    COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_MIDDLE_BUTTON = 16, // 0x00000010
    COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON1 = 32, // 0x00000020
    COREWEBVIEW2_MOUSE_EVENT_VIRTUAL_KEYS_X_BUTTON2 = 64, // 0x00000040
  }
}
