// Decompiled with JetBrains decompiler
// Type: WebView2.COREWEBVIEW2_PROCESS_FAILED_REASON
// Assembly: WebView2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: CB197DC1-34BC-456D-8BC3-B58B9CD2508E
// Assembly location: O:\webview2\v1086435\WebView2.dll

namespace Diga.WebView2.Interop
{
  public enum COREWEBVIEW2_PROCESS_FAILED_REASON
  {
    COREWEBVIEW2_PROCESS_FAILED_REASON_UNEXPECTED,
    COREWEBVIEW2_PROCESS_FAILED_REASON_UNRESPONSIVE,
    COREWEBVIEW2_PROCESS_FAILED_REASON_TERMINATED,
    COREWEBVIEW2_PROCESS_FAILED_REASON_CRASHED,
    COREWEBVIEW2_PROCESS_FAILED_REASON_LAUNCH_FAILED,
    COREWEBVIEW2_PROCESS_FAILED_REASON_OUT_OF_MEMORY,
  }
}
