// Decompiled with JetBrains decompiler
// Type: WebView2.WEBVIEW2_WEB_ERROR_STATUS
// Assembly: WebView2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5F0D75F7-60BF-43BB-8231-ACD9063B7411
// Assembly location: O:\macos\WebView2.dll

namespace Diga.WebView2.Interop
{
  public enum WEBVIEW2_WEB_ERROR_STATUS
  {
    WEBVIEW2_WEB_ERROR_STATUS_UNKNOWN,
    WEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_COMMON_NAME_IS_INCORRECT,
    WEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_EXPIRED,
    WEBVIEW2_WEB_ERROR_STATUS_CLIENT_CERTIFICATE_CONTAINS_ERRORS,
    WEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_REVOKED,
    WEBVIEW2_WEB_ERROR_STATUS_CERTIFICATE_IS_INVALID,
    WEBVIEW2_WEB_ERROR_STATUS_SERVER_UNREACHABLE,
    WEBVIEW2_WEB_ERROR_STATUS_TIMEOUT,
    WEBVIEW2_WEB_ERROR_STATUS_ERROR_HTTP_INVALID_SERVER_RESPONSE,
    WEBVIEW2_WEB_ERROR_STATUS_CONNECTION_ABORTED,
    WEBVIEW2_WEB_ERROR_STATUS_CONNECTION_RESET,
    WEBVIEW2_WEB_ERROR_STATUS_DISCONNECTED,
    WEBVIEW2_WEB_ERROR_STATUS_CANNOT_CONNECT,
    WEBVIEW2_WEB_ERROR_STATUS_HOST_NAME_NOT_RESOLVED,
    WEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED,
    WEBVIEW2_WEB_ERROR_STATUS_REDIRECT_FAILED,
    WEBVIEW2_WEB_ERROR_STATUS_UNEXPECTED_ERROR,
  }
}
