// Decompiled with JetBrains decompiler
// Type: WebView2.CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT
// Assembly: WebView2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 390039CF-BF77-421E-8AE4-CC8FD0DF2A08
// Assembly location: O:\dev\webview2-interop-master\Src\WebView2.dll

namespace Diga.WebView2.Interop
{
  public enum CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT
  {
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_ALL,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_FONT,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_PING,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT,
    CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER,
  }
}
