// Decompiled with JetBrains decompiler
// Type: WebView2.CORE_WEBVIEW2_PERMISSION_KIND
// Assembly: WebView2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 390039CF-BF77-421E-8AE4-CC8FD0DF2A08
// Assembly location: O:\dev\webview2-interop-master\Src\WebView2.dll

namespace Diga.WebView2.Interop
{
  public enum CORE_WEBVIEW2_PERMISSION_KIND
  {
    CORE_WEBVIEW2_PERMISSION_KIND_UNKNOWN_PERMISSION,
    CORE_WEBVIEW2_PERMISSION_KIND_MICROPHONE,
    CORE_WEBVIEW2_PERMISSION_KIND_CAMERA,
    CORE_WEBVIEW2_PERMISSION_KIND_GEOLOCATION,
    CORE_WEBVIEW2_PERMISSION_KIND_NOTIFICATIONS,
    CORE_WEBVIEW2_PERMISSION_KIND_OTHER_SENSORS,
    CORE_WEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ,
  }
}
