// Decompiled with JetBrains decompiler
// Type: WebView2.WEBVIEW2_PERMISSION_TYPE
// Assembly: WebView2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5F0D75F7-60BF-43BB-8231-ACD9063B7411
// Assembly location: O:\macos\WebView2.dll

namespace Diga.WebView2.Interop
{
  public enum WEBVIEW2_PERMISSION_TYPE
  {
    WEBVIEW2_PERMISSION_TYPE_UNKNOWN_PERMISSION,
    WEBVIEW2_PERMISSION_TYPE_MICROPHONE,
    WEBVIEW2_PERMISSION_TYPE_CAMERA,
    WEBVIEW2_PERMISSION_TYPE_GEOLOCATION,
    WEBVIEW2_PERMISSION_TYPE_NOTIFICATIONS,
    WEBVIEW2_PERMISSION_TYPE_OTHER_SENSORS,
    WEBVIEW2_PERMISSION_TYPE_CLIPBOARD_READ,
  }
}
