// Decompiled with JetBrains decompiler
// Type: WebView2.WEBVIEW2_WEB_RESOURCE_CONTEXT
// Assembly: WebView2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 5F0D75F7-60BF-43BB-8231-ACD9063B7411
// Assembly location: O:\macos\WebView2.dll

namespace Diga.WebView2.Interop
{
  public enum WEBVIEW2_WEB_RESOURCE_CONTEXT
  {
    WEBVIEW2_WEB_RESOURCE_CONTEXT_ALL,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_STYLESHEET,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_IMAGE,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_MEDIA,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_FONT,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_SCRIPT,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_XML_HTTP_REQUEST,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_FETCH,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_TEXT_TRACK,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_EVENT_SOURCE,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_WEBSOCKET,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_MANIFEST,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_SIGNED_EXCHANGE,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_PING,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_CSP_VIOLATION_REPORT,
    WEBVIEW2_WEB_RESOURCE_CONTEXT_OTHER,
  }
}
