// Decompiled with JetBrains decompiler
// Type: Diga.WebView2.Interop.COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND
// Assembly: Diga.WebView2.Interop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: EA95D0FC-77DE-40CE-8C3C-89517DF28E5B
// Assembly location: O:\webview2\V10118539\Diga.WebView2.Interop.dll

namespace Diga.WebView2.Interop
{
  public enum COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND
  {
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_PAGE,
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_IMAGE,
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_SELECTED_TEXT,
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_AUDIO,
    COREWEBVIEW2_CONTEXT_MENU_TARGET_KIND_VIDEO,
  }
}
